clc;
close all;
ant = fractalCarpet('Substrate',dielectric('FR4'));
show(ant);
figure;
pattern(ant,5.45e9);
figure;
ant2 = fractalKoch('NumIterations',3,'Type','loop');
show(ant2);
figure;
pattern(ant2,5.45e9);
figure;
ant = fractalIsland('Substrate',dielectric('FR4'));
show(ant);
figure;
pattern(ant,6e9);
figure;
ant = fractalGasket;
show(ant);
figure;
pattern(ant,6e9);
