clc;
clear all;
close all;
f1=input('enter frequency:');
f2=input('enter frequency:');
fs=input('enter sampling frequency:');
t=0:0.001:1;
x=10*sin(2*pi*f1*t);
subplot(4,1,1);
plot(x);
title('wave 1');
y=10*sin(2*pi*f2*t);
subplot(4,1,2);
plot(y);
title('wave 2');
xy=x+y;
subplot(4,1,3);
plot(xy);
title('final wave');
n=0:(2*fs)-1;
y=10*sin(2*pi*(f1+f2)*n/fs);
%figure;
subplot(4,1,4);
stem(n,y);
title('sampled wave');
